/*GERENCIAMENTO DE CONTROLE*/

CREATE USER  'nome usuário'@'local' IDENTIFIED BY '123456'; /*CRIAÇÃO USUÁRIO*/
CREATE USER  'nome usuário'@'localhost' IDENTIFIED BY '123456'; /*CRIAÇÃO USUÁRIO LOCAL*/
CREATE USER  'nome usuário'@ '%' IDENTIFIED BY '123456'; /*CRIAÇÃO USUÁRIO PODE ACESSAR DE QUALQUER LOCAL*/

GRANT ALL ON Curso_SQL.* TO 'usuario'@'localhost'; /*PRIVILÉGIO TOTAL AO BANCO PARA O USUÁRIO*/

CREATE USER 'Alex'@'%' IDENTIFIED BY 'viagem';/*CRIAÇÃO DE UM USUÁRIO QUE PODE ACESSAR DE QUALQUER IP*/
GRANT SELECT ON Curso_SQL.* TO 'Alex'@'%';/*PODE APENAS LER OS DADOS DE TODAS AS TABELAS*/
GRANT INSERT ON Curso_SQL.funcionarios TO 'Alex'@'%';/*PODE INSERIR DADOS NA TABELA FUNCIONÁRIOS*/

REVOKE INSERT ON Curso_SQL.funcionarios FROM 'Alex'@'%';/*REMOVE OS PRIVILÉGIOS DE INSERIR DADOS*/
REVOKE SELECT ON Curso_SQL.* FROM 'Alex'@'%';/*REMOVE OS PRIVILÉGIOS DE LEITURA DO USUÁRIO*/

DROP USER 'Alex'@'%';/*EXCLUI USUÁRIO VIAJANTE*/
DROP USER 'usuario'@'localhost';/*EXCLUI USUÁRIO LOCAL*/

SELECT USER FROM mysql.user;/*MOSTRA OS USUÁRIOS QUE TEM ACESSO AO BANCO*/
